import os
import sys
import glob
import cv2
import numpy as np
import argparse
import shutil
import subprocess
import json

# Dynamically get absolute paths
current_script_dir = os.path.dirname(os.path.abspath(__file__))
project_root_dir = os.path.abspath(os.path.join(current_script_dir, ".."))
sys.path.append(project_root_dir)

from utils.diffusion_utils import run_sd_inpainting, get_auto_keyframe_indices
from utils.mask_utils import generate_random_stationary_mask, save_stationary_mask_sequence
from utils.metrics import evaluate_video_quality

def parse_args():
    parser = argparse.ArgumentParser(description="Part 3: Dual-Track Evaluation (Qualitative & Quantitative)")
    parser.add_argument("--dataset_name", type=str, required=True, help="e.g., tennis")
    parser.add_argument("--prompt", type=str, required=True, help="Prompt for SD")
    
    # Qualitative Args (Dynamic Mask)
    parser.add_argument("--gt_data_dir", type=str, default=None, help="Path to original frames with dynamic objects")
    parser.add_argument("--gt_mask_dir", type=str, default=None, help="Path to dynamic GT masks")
    
    # Quantitative Args (Stationary Mask)
    parser.add_argument("--clean_data_dir", type=str, default=None, help="Path to clean GT video frames for metrics")
    
    parser.add_argument("--n_keyframes", type=int, default=3, help="Number of SD keyframes (default: 3)")
    parser.add_argument("--output_base_dir", type=str, default=os.path.join(project_root_dir, "results", "part3_evaluation"))
    return parser.parse_args()

def run_propainter(data_dir, mask_dir, output_dir):
    """Helper function to execute ProPainter via subprocess with path injection."""
    propainter_dir = os.path.join(project_root_dir, "third_party", "ProPainter")
    propainter_script = os.path.join(propainter_dir, "inference_propainter.py")
    
    custom_env = os.environ.copy()
    custom_env["PYTHONPATH"] = project_root_dir + os.pathsep + custom_env.get("PYTHONPATH", "")
    
    try:
        subprocess.run([
            sys.executable, propainter_script,
            "--video", os.path.abspath(data_dir),
            "--mask", os.path.abspath(mask_dir),
            "--output", os.path.abspath(output_dir)
        ], check=True, cwd=propainter_dir, env=custom_env, stdout=subprocess.DEVNULL) # 隐藏冗长输出
    except subprocess.CalledProcessError as e:
        print(f"[Error] ProPainter execution failed: {e}")

def load_frames_from_dir(folder_path):
    files = sorted(glob.glob(os.path.join(folder_path, "*.[pj][np][g]")))
    return [cv2.imread(f) for f in files]

def extract_frames_from_propainter_output(output_dir, expected_count):
    """
    Robustly extracts output frames from ProPainter's output directory.
    ProPainter usually saves to output_dir/inpaint_out/out.mp4.
    """
    # Look for mp4 video generated by ProPainter
    mp4_files = glob.glob(os.path.join(output_dir, "**", "*.mp4"), recursive=True)
    frames = []
    
    if mp4_files:
        cap = cv2.VideoCapture(mp4_files[0])
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            frames.append(frame)
        cap.release()
    else:
        # Fallback: look for images if it didn't save an mp4
        img_files = sorted(glob.glob(os.path.join(output_dir, "**", "*.png"), recursive=True))
        frames = [cv2.imread(f) for f in img_files]

    # Truncate to match exact length in case video writer added/dropped a frame
    if len(frames) >= expected_count:
        return frames[:expected_count]
    elif len(frames) > 0:
        print(f"[Warning] Extracted {len(frames)} frames, expected {expected_count}.")
        return frames
    else:
        return []

def run_pipeline(data_dir, mask_dir, output_dir, dataset_name, prompt, n_keyframes, is_stationary=False):
    """
    Core pipeline that runs Baseline and Generative ProPainter.
    Returns the path to the output directories.
    """
    img_files = sorted(glob.glob(os.path.join(data_dir, "*.[pj][np][g]")))
    mask_files = sorted(glob.glob(os.path.join(mask_dir, "*.png")))
    total_frames = len(img_files)

    injected_data_dir = os.path.join(output_dir, "sd_injected_frames")
    injected_mask_dir = os.path.join(output_dir, "sd_injected_masks")
    baseline_out_dir = os.path.join(output_dir, "baseline_propainter")
    generative_out_dir = os.path.join(output_dir, "generative_propainter")
    
    for d in [injected_data_dir, injected_mask_dir, baseline_out_dir, generative_out_dir]:
        os.makedirs(d, exist_ok=True)

    # 1. Run Baseline ProPainter
    print(f"      -> Running Baseline ProPainter...")
    run_propainter(data_dir, mask_dir, baseline_out_dir)

    # 2. Generative Approach - SD Keyframe Injection
    print(f"      -> Preparing SD Keyframes (Ours)...")
    target_indices = get_auto_keyframe_indices(total_frames, n_keyframes)
    
    for idx, img_path in enumerate(img_files):
        filename = os.path.basename(img_path)
        img_out_path = os.path.join(injected_data_dir, filename)
        
        # Match mask filename
        if is_stationary:
            mask_filename = os.path.splitext(filename)[0] + '.png'
        else:
            mask_filename = os.path.basename(mask_files[idx])
            
        mask_path = os.path.join(mask_dir, mask_filename)
        mask_out_path = os.path.join(injected_mask_dir, mask_filename)

        if idx in target_indices:
            print(f"         [Anchor {idx}] Inpainting with Stable Diffusion...")
            run_sd_inpainting(img_path, mask_path, prompt, img_out_path)
            # The Injection Trick: Zero out the mask so ProPainter thinks it's clean
            blank_mask = np.zeros_like(cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE))
            cv2.imwrite(mask_out_path, blank_mask)
        else:
            shutil.copy(img_path, img_out_path)
            shutil.copy(mask_path, mask_out_path)

    # 3. Run Generative ProPainter
    print(f"      -> Running Generative ProPainter (Ours)...")
    run_propainter(injected_data_dir, injected_mask_dir, generative_out_dir)

    return baseline_out_dir, generative_out_dir, total_frames

def main():
    args = parse_args()
    
    print(f"\n{'='*60}\nPart 3: Generative Evaluation Pipeline for [{args.dataset_name}]\n{'='*60}")
    
    # ==========================================
    # Track A: Qualitative Evaluation (Dynamic Mask)
    # ==========================================
    if args.gt_data_dir and args.gt_mask_dir:
        print("\n>>> Starting Qualitative Evaluation (Dynamic Masking) <<<")
        qualitative_out_dir = os.path.join(args.output_base_dir, args.dataset_name, "qualitative")
        
        base_dir, gen_dir, _ = run_pipeline(
            args.gt_data_dir, args.gt_mask_dir, qualitative_out_dir, 
            args.dataset_name, args.prompt, args.n_keyframes, is_stationary=False
        )
        print(f" [Success] Visual results saved. You can check the mp4 files in:")
        print(f"   Baseline: {base_dir}")
        print(f"   Ours:     {gen_dir}")
    
    # ==========================================
    # Track B: Quantitative Evaluation (Stationary Mask)
    # ==========================================
    if args.clean_data_dir:
        print("\n>>> Starting Quantitative Evaluation (Stationary Masking) <<<")
        quant_out_dir = os.path.join(args.output_base_dir, args.dataset_name, "quantitative")
        os.makedirs(quant_out_dir, exist_ok=True)
        
        clean_img_files = sorted(glob.glob(os.path.join(args.clean_data_dir, "*.[pj][np][g]")))
        if not clean_img_files:
            print("[Error] No clean frames found.")
            return
            
        # 1. Generate Stationary Mask
        print("      -> Generating Random Stationary Mask...")
        sample_frame = cv2.imread(clean_img_files[0])
        H, W, _ = sample_frame.shape
        stat_mask = generate_random_stationary_mask(H, W, num_strokes=8, base_thickness=45)
        
        stationary_mask_dir = os.path.join(quant_out_dir, "stationary_masks")
        frame_names = [os.path.basename(f) for f in clean_img_files]
        save_stationary_mask_sequence(stat_mask, stationary_mask_dir, len(clean_img_files), frame_names)

        # 2. Run Pipeline
        base_dir, gen_dir, total_frames = run_pipeline(
            args.clean_data_dir, stationary_mask_dir, quant_out_dir, 
            args.dataset_name, args.prompt, args.n_keyframes, is_stationary=True
        )

        # 3. Extract Frames & Calculate Metrics
        print("      -> Extracting Frames and Calculating Metrics...")
        gt_frames = load_frames_from_dir(args.clean_data_dir)
        baseline_frames = extract_frames_from_propainter_output(base_dir, total_frames)
        generative_frames = extract_frames_from_propainter_output(gen_dir, total_frames)

        if len(gt_frames) == len(baseline_frames) == len(generative_frames) > 0:
            metrics = {
                "Baseline_Pure_ProPainter": evaluate_video_quality(baseline_frames, gt_frames),
                "Ours_SD_ProPainter": evaluate_video_quality(generative_frames, gt_frames)
            }
            
            print("\n" + "="*40)
            print(" 🏆 Quantitative Results (SSIM & PSNR)")
            print("="*40)
            print(f"Baseline (Pure ProPainter): PSNR: {metrics['Baseline_Pure_ProPainter']['PSNR']:.2f}, SSIM: {metrics['Baseline_Pure_ProPainter']['SSIM']:.4f}")
            print(f"Ours (SD + ProPainter):     PSNR: {metrics['Ours_SD_ProPainter']['PSNR']:.2f}, SSIM: {metrics['Ours_SD_ProPainter']['SSIM']:.4f}")
            print("="*40)
            
            with open(os.path.join(quant_out_dir, "evaluation_metrics.json"), "w") as f:
                json.dump(metrics, f, indent=4)
        else:
            print(f"[Error] Metric Calculation Failed. Counts - GT: {len(gt_frames)}, Base: {len(baseline_frames)}, Gen: {len(generative_frames)}")
            
    print("\n[Done] Pipeline Execution Finished.")

if __name__ == '__main__':
    main()